const countries = new Map();
countries.set('argentina', 'ar');
countries.set('united arab emirates', 'ae');
countries.set('uae', 'ae')
countries.set('austria', 'at');
countries.set('australia', 'au');
countries.set('belgium', 'be');
countries.set('bulgaria', 'bg');
countries.set('brazil', 'br');
countries.set('canada', 'ca');
countries.set('china', 'cn');
countries.set('switzerland', 'ch');
countries.set('colombia', 'co');
countries.set('cuba', 'cu');
countries.set('germany', 'de');
countries.set('czech republic', 'cz');
countries.set('egypt', 'eg');
countries.set('france', 'fr');
countries.set('united kingdom', 'gb');
countries.set('uk', 'gb');
countries.set('england', 'gb');
countries.set('greece', 'gr');
countries.set('hong kong', 'hk');
countries.set('hungary', 'hu');
countries.set('indonesia', 'id');
countries.set('ireland', 'ie');
countries.set('israel', 'il');
countries.set('india', 'in');
countries.set('italy', 'it');
countries.set('japan', 'jp');
countries.set('south korea', 'kr');
countries.set('lithuania', 'lt');
countries.set('latvia', 'lv');
countries.set('morocco', 'ma');
countries.set('mexico', 'mx');
countries.set('malaysia', 'my');
countries.set('nigeria', 'ng');
countries.set('netherlands', 'nl');
countries.set('norway', 'no');
countries.set('new zealand', 'nz');
countries.set('phillipines', 'pl');
countries.set('poland', 'pl');
countries.set('portugal', 'pt');
countries.set('romania', 'ro');
countries.set('serbia', 'rs');
countries.set('russia', 'ru');
countries.set('saudi arabia', 'sa');
countries.set('singapore', 'sg');
countries.set('slovenia', 'si');
countries.set('slovakia', 'sk');
countries.set('thailand', 'th');
countries.set('turkey', 'tr');
countries.set('taiwan', 'tw');
countries.set('ukraine', 'ua');
countries.set('united states', 'us');
countries.set('united states of america', 'us');
countries.set('us', 'us');
countries.set('venezuela', 've');
countries.set('south africa', 'za');
export default countries;